### ISSUE TITLE
Readme inacuracy

### ISSUE THREAD

**Issue by henroFall** [itiligent/Guacamole-Installer#46]
**Describe the issue:**
The readme says, "To upgrade Guacamole, edit upgrade-guacamole.sh to reflect the latest versions of Guacamole & MySQL connector/J before running," however, there is no method to update the MySQL Connector/J version in the config file. Only the Guacamole version exists.

**Steps to reproduce the issue:**
Try to follow readme, get confused when searching for the value to change for the MySQL connector/J.

**Describe the software environment:**
n/a

**Logs / screenshots / error outputs etc**
n/a

**Troubleshooting steps already taken?:**
Simply change the guacamole version and continue, the update works. 

Suggest changing the README to instruct the user to only update the version of Guacamole.

**Comment by itiligent** [comment]
Please do a simple search for "connector" in the upgrade script and this will lead you to the top of the script at line 53 . The following line is directly beneath the NEW_GUAC_VERSION (which you have already discovered and applied):

```
MySQL Connector/J version. See https://dev.mysql.com/downloads/connector/j/ for latest version number.
NEW_MYSQLJCON="8.4.0"
```

**Comment by henroFall** [comment]
It looks like my upgrade script file is old. I skimmed the one here and I
don't see that it updates itself, but I didn't really study it so maybe it
does now.

I ran this older upgrade script against 1.5.4 and upgraded it to 1.5.5 and
it seems to be working fine. I guess I'll just lurk and once you do a next
revision, I'll be sure to grab a fresh upgrade script before trying
anything.

Thanks for cluing me in! I would have kept running this old thing until
something really broke one day.

**Comment by itiligent** [comment]
as the scripts update during first install  the settings chosen at first install, taking a later script version will work fine if you take some time to adjust the variablrs (Eg NAME= ) to suit the original specific setup.  One day I might change the structure so all updates are centrally captured, but that might be overkill.
