### ISSUE TITLE
how to create licence for guacamole

### ISSUE THREAD

**Issue by akhakpash** [itiligent/Guacamole-Installer#47]
How can we create a time activation for the Guacamole license service when this service stops working at a specified time?

**Comment by akhakpash** [comment]
How can we create a timed activation for the Guacamole license service when the service is down at a certain time?
Or how can I stop nginx service with scheduled time in Ubuntu Linux and not need changes

**Comment by itiligent** [comment]
to help me understand your question, I need to ask what is your end goal?

 Do you want to limit a specfic Gucamole USER (or group of users) access to remote connections to only a certain period of the day?
or
Do you want to limit the availabiltiy of the WHOLE SYSTEM to accept USER logins based on a time of day?
or 
Do you want to limit a specifc Guacamole connection to a time of day for any user?

**Comment by akhakpash** [comment]
I want to limit the availability of the entire system to accept user logins based on monthly time.
