### ISSUE TITLE
MYSQL Password is not set / empty

### ISSUE THREAD

**Issue by schleicherdeha** [itiligent/Guacamole-Installer#49]
There is no prompt for the Password for MYSQL, so it seems that it's empty. If i understand it right, it is inserted in the backup-guacamole.sh

This in my case is:

GUAC_USER='guacamole_user'
GUAC_PWD=''

Could you check this please?

Kind regards

**Comment by itiligent** [comment]
I updated the download link to use curl but I left a bug that skipped saving the setup script locally before execution. It prompts as normal now, so try again with:
```
curl -sSL https://raw.githubusercontent.com/itiligent/Guacamole-Install/main/1-setup.sh -o 1-setup.sh && bash 1-setup.sh
```
