### ISSUE TITLE
How can I change this text => GUACAMOLE PROXY PARAMETERS (GUACD)

### ISSUE THREAD

**Issue by akhakpash** [itiligent/Guacamole-Installer#51]
How can I change this text?
GUACAMOLE PROXY PARAMETERS (GUACD)
![Capture](https://github.com/user-attachments/assets/2e5fca7a-4b7a-49c8-b3ea-d7b3adb51778)

**Comment by itiligent** [comment]
no sure what your purpose is here - it looks like you want to re-brand Gucamole? Actually your here question is the same question you already asked in #52,  so please look to the answer I gave you there.
