### ISSUE TITLE
How can I change this text => Connected to Guacamole...

### ISSUE THREAD

**Issue by akhakpash** [itiligent/Guacamole-Installer#52]
How can I change this text?
![Untitled](https://github.com/user-attachments/assets/3ae79577-bf7d-4357-a2e9-0d74ebc43013)

**Comment by itiligent** [comment]
I dont know for sure, but you can probabbly change this with time and effort.  
As with any open source, to try this, you need to searching through and editing the source code befire it compiles. The install script provides a prompt at the start to exit after downloading only the sources so you can do this. You will need to search among the source for the specific string(s) of text and test till you figure it out. You would then need to add lines to automate those changes programatiicaly to the souce in the upgrade script, or make this change manually fir each upgrade or install.

**Comment by itiligent** [comment]
Another thought, you might be able to edit after compilation in the Tomcat directories somewhere.. again, time and effort is required to seek out this level of editable detail in the code or what is compiled into binaries. Generally I find that making too many changes to the Tomcat configuration away from default Guacmole settings risks breaking various things when it comes to upgrades. Also, as Tomcat packages change, the way you solve this in future may also change.

**Comment by itiligent** [comment]
a clarification to my first post..
To halt the script and edit source before compiling, there is a prompt option that is currently disabled that I forgot to mention.
To stop the script just before build time, uncommned this line in 2-install-guacamole.sh
```
read -p $'Script paused for editing source before building. Enter to begin the build...\n'
```
Then you will be free to search the extracted sources and make your changes

**Comment by itiligent** [comment]
closed as answered
