### ISSUE TITLE
Creating a temporary license to perform the work

### ISSUE THREAD

**Issue by akhakpash** [itiligent/Guacamole-Installer#53]
How can I create a license that automatically stops the program at a specified time?
I want to limit the availability of the entire system to accept user logins based on monthly time.

**Comment by itiligent** [comment]
Guacamole does not require a licence to connect to it, so in that context there is nothing to revoke. Your question can only be handled by looking at login access time or network access times....

Your choices are to 
- apply time limits to the available login hours for each account in Gucamole , 
- Integrate Guacamole authentication with some other 3rd party authentication platform and  apply whatever login time restrictions that that authentication platform supports - coild be dont with group policy in the case of LDAP.
- To drop access to the whole system for specific time windows, then you need to look at some other network (or Nginx proxy based) firewall rule or cron shedule outside of Guacaomle.  

The last 2 points will largely come down to your specific environemnt and available skills as to how you would acheive any of the above.

**Comment by itiligent** [comment]
closed as answered
