### ISSUE TITLE
Licence active Guacamole

### ISSUE THREAD

**Issue by akhakpash** [itiligent/Guacamole-Installer#54]
I want to limit the availability of the entire system to accept user logins based on monthly time.
what shoud i to do

**Comment by akhakpash** [comment]
In fact, I want the guacamole service to be completely stopped after the period that I apply to the license

**Comment by itiligent** [comment]
Hi,
I have already answered this - see  #53. 

Again, a complete service stop will relate to a Linux sheduled task using cron. You could stop just Nginx, or you could stop the network firewall, or you could stop the Guac server. It all depends on what you are trying to acheive.

How you do thins  will all come down to your Linux skils, and not Guacmole skills so much. With respect, that fact that you are asking this type of question suggests you may need to take some time getting to know Linux a little better.   You will need to put in the time to learn Linux and how to stop / start services, and how to apply schedules with cron. Google is your best friend!

Also, can I please aks that you do not create a new issue for each time you ask a related question, please keep using the same thread already created. Thankyou,
