### ISSUE TITLE
OTP-SMS

### ISSUE THREAD

**Issue by akhakpash** [itiligent/Guacamole-Installer#56]
I used Google Authenticator to get the authentication token. I wanted to receive the created token through the GSM modem.
What code can I use for this and software development?
Suppose I have the necessary IPA from the modem side, what code needs to be created in the program to send token message 
thank you so much

**Comment by akhakpash** [comment]
I have the necessary **API** from the modem side, what code needs to be created in the program to send token message
thank you so much

**Comment by itiligent** [comment]
Hi,
I've been quite ok with putting time into helping you with several other of your off topic questions, but you have drifted far away from the install script topic here and seem to be seeking free consulting on a rather complex commercial product you are building. 

What I think you are looking for is a set of python type functions that relate to serial modem manangment & Linux shell to SMS integrated messaging, all tied into the 3rd party OTP java extension outputs somehow - nothing to do with Guacamole itself. 

I'm very happy to address Guacamole installation specific items within th scope of the script and its use, but please rember this repo is free software.  For some inspirtation with creating OTP challenges in the linux shell and interating these though SMS, take a look at my repo https://github.com/itiligent/SMS-to-Shell.

I wish you luck on your project.

**Comment by akhakpash** [comment]
hello
Thank you for your professional behavior that you are ready to solve the challenges of the guacamole program with dear friends.
I don't want any misunderstanding, my opinion about guacamole and the questions I am asking are my knowledge and I don't need to commercialize this product.
Because the point of view of programming and analysis and work methods are important to me
And thank you for answering my initial question
I sincerely thank you for your efforts in this regard and for answering my questions
