### ISSUE TITLE
Add language

### ISSUE THREAD

**Issue by akhakpash** [itiligent/Guacamole-Installer#57]
Hello
How can add the required language ?
Setting=>Preferences=>Display language
thank you

**Comment by itiligent** [comment]
If your language is not supported you need to build your own version of the guacamole.war file with your own your custom translation file in inclued in it. This method will also answer an earlier wquestion you had about changing text in the console.

### Make the custom translaton file changes
`sudo apt update && sudo apt install git`
`git clone https://github.com/apache/guacamole-client.git`

a. Go to `guacamole-client/guacamole/src/main/frontend/src/src/translations` and choose a translation file you dont expect to need. eg de.json
b. The translaton files are actuall  a template for all of the whole console text - (answers your earlier question how to make visual changes). Just edit the json file as as you need.
c. For later ease of testing, also make a copy of `en.json` and rename this `test.json` in the same translations direcroty.
d. Inside `test.json` change  `"NAME" : "English",` to  `"NAME" : "Test",`

_You might want to research how to have Guacamole recognise a totally new translation json file, I dont know how, something to do with manifiest maybe._


### Get the client build Java prerequisites  
3. You need to install an older version of Jdk 8.0._411 to build the guac client from source

```
https://www.oracle.com/java/technologies/javase/javase8u211-later-archive-downloads.html (needs oracle sign in)
select the Linux x64 Compressed Archive and copy it to where you will be compiling
sudo mkdir -p /usr/lib/jvm
sudo tar zxvf jdk-8u411-linux-x64.tar.gz -C /usr/lib/jvm
sudo update-alternatives --install "/usr/bin/java" "java" "/usr/lib/jvm/jdk1.8.0_411/bin/java" 1
sudo update-alternatives --set java /usr/lib/jvm/jdk1.8.0_411/bin/java
```

### Install maven and then build the new war file 
`sudo apt install maven`
 `cd ~/guacamole-client`  # change to the root of the cloned source 
`mvn package`
When the build completes the new .war file is found in `guacamole-client/guacamole/target`

### Install the war file into Guacamole
`sudo mv -f guacamole-1.5.5.war /etc/guacamole/guacamole.war` # copy and rename the new war file 
`sudo chmod 664 /etc/guacamole/guacamole.war`
`sudo ln -sf /etc/guacamole/guacamole.war /var/lib/tomcat9/webapps/`
`sudo systemctl restart tomcat9 && sudo systemctl restart guacd`

###
Login to guacamole. The new Test language file will be in the dropdown box. By selecting Test it becomes very easy identify ee the specic header names you might want to edit. Keep working through this process till you get all the content you want changed. 

![Capture1](https://github.com/user-attachments/assets/4e3abb41-2340-4035-94ba-d20c35109931)
 Test

![Capture2](https://github.com/user-attachments/assets/2b9ffa9c-c840-4b2e-a0f3-86d1e54a430e)

**Comment by akhakpash** [comment]
root@pam:/etc/guacamole/guacamole-client/guacamole# sudo update-alternatives --config java
There are 2 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                         Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java   1111      auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java   1111      manual mode
* 2            /usr/lib/jvm/jdk1.8.0_411/bin/java            1         manual mode

**Comment by itiligent** [comment]
The commands work on a fresh build machine when you follow them in the exact order I gave you. Thats how I got the screen shots!  

Please dont post only log dumps without a question or explaination of  how you got here, or nothing about your environment or what troublshooting steps you've taken.  As such I can only guess that you probably had a later version of java jdk before installing the older JDK 8  - and you are liekly trying to build with is on the same guac machine itelf. 

The logs and outputs, conbined with my instructions are telling you all you need. Guac needs v8 to build, but your default  jdk is a later version and you are calling the wrong one.  Please take the time to inpterpret commands I've given you in this context, these commands given reset the jdk 8 to the correct priority. Currently you have jdk 8 at priority 2, not 1. 

If you installed jdk8 before maven and set all the priority commands I've given you in order, it will work on a fresh machine. 

Simple things to try might be uninstalling the newer  jdk - that way there is no conflict in the first place. (not tested, but worth a look)
