### ISSUE TITLE
 Where is it stored record session

### ISSUE THREAD

**Issue by akhakpash** [itiligent/Guacamole-Installer#58]
Can you tell me when the user connects to the server, the saved file Typescript path:
 Where is it stored?

**Comment by akhakpash** [comment]
How can I transfer saved files to another server?
Better to say: another server where session records are stored
By default, I created the storage location in Recording path option: ${HISTORY_PATH}/${HISTORY_UUID}. What command line should I send to another server?

**Comment by akhakpash** [comment]
![Capture](https://github.com/user-attachments/assets/f13d2417-c2d5-4374-8b23-14a6da9f77eb)

**Comment by itiligent** [comment]
This forum is for the benefit of script users looking to resolve common issues with the *install script*. You continue to post many unrelated questions that relate to many other linux or unrealted config skills that are better served by google or other support forums.  Closing.
