### ISSUE TITLE
Prompt from certificate duration even if variable is set in the script

### ISSUE THREAD

**Issue by ddieffen** [itiligent/Guacamole-Installer#60]
**Describe the issue:**
After filling out the duration of 3650 days in the parameters of 1-Setup.sh there is a prompt during installation that asks for that duration again.

**Steps to reproduce the issue:**
Fill out 1-setup.sh with the desired parameter for CERT_DAYS and run the installation. A prompt asks for the duration during the installation.

**Describe the software environment:**
Ubuntu 22.04

**Comment by itiligent** [comment]
Well spotted.  The script now skips the prompt if the CERT_DAYS value is not blank.
