### ISSUE TITLE
Can't connect to WS2012 but Works on WS2019

### ISSUE THREAD

**Issue by milocheri** [itiligent/Guacamole-Installer#63]
Hello, first of all, thank you for the script, it works like a charm !

I just start adding WS devices , and i can confirm works fine with WS2019/WS2016 and WS2022, however, when i tried to connect to a WS2012 im getting errors

i didn't know where to find the logs, i figure out in journalctl, this is the line when i tried to connect to a WS2012

![image](https://github.com/user-attachments/assets/a19233be-9d6e-4073-832d-7c813c4799cb)

**Comment by itiligent** [comment]
Your issue likely relates to older TLS version support. This situtation is addressed directly in the readme:

_"Nginx reverse proxy is configured to default to at least TLS 1.2. For ancient systems, see commented sections of the /etc/nginx/nginx.conf file after install."_

For various security compliance tests, the Guacamole install script updates the default /etc/nginx.conf from
```
# SSL Settings
ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
```
to 
```
# SSL Settings
ssl_protocols TLSv1.2 TLSv1.3;
```
Reverting this line in the nginx.conf and restarting nginx file will once again allow older TLS 1.1 to pass through nginx.

**Comment by milocheri** [comment]
Thanks fot the quick reply & sorry to reopen, i've been searching for the file /etc/nginx/nginx.conf, but i dont even have the nginx directory, during the installation, in "Protect guacamole behind nginx reverse proxy, i choose the default option wich is No, so where should i search those settings ? thanks again!

**Comment by itiligent** [comment]
You havent taken the time to provide any background information about your settings , so I cant offer you much more than suggest you look at trying differernt security mode settings when setting up the RDP connection. This is not an new questtion btw.. a 5 sec google gave me : https://sourceforge.net/p/guacamole/discussion/1110834/thread/b63b6dd5/
Try  NLA and also check ignore certificate settings.

![Screenshot from 2024-10-03 14-36-42](https://github.com/user-attachments/assets/717125fe-2d9a-4abd-a017-5e1a40e84595)

**Comment by milocheri** [comment]
Thank yoou again, i did the installation with your script, the machine is a LXC container running debian 12 on Proxmox, i already all the settings and also with NLA and ignore certificate, and it doesnt works
![image](https://github.com/user-attachments/assets/bdde693e-7b22-4a0f-8c20-bbe125fa787d)
![image](https://github.com/user-attachments/assets/4c67ebe4-e3ca-4978-9ab2-46c193dc9666)

**Comment by itiligent** [comment]
Did you upgrade guacamole? If so delete old connection object and create new. 

Setting the connection mode in gucamole to "RDP encryption", (windows 7 needs this so might work) 

also try various windows settgings here: 
![Screenshot from 2024-10-03 16-03-17](https://github.com/user-attachments/assets/f24859c3-80ab-4851-91aa-912bc5e7fd41)

**Comment by itiligent** [comment]
I can successfully use Guacamole 1.5.5 to connect to Windows Server 2012 using the following settings:
![Screenshot from 2024-10-03 17-15-56](https://github.com/user-attachments/assets/1a72bb1f-6b72-48ea-9533-35ea375e7f1c)
and 
![Screenshot from 2024-10-03 17-16-43](https://github.com/user-attachments/assets/f8da3400-c884-47c4-8dfa-2d328b75962d)

**Comment by milocheri** [comment]
Something really weird happens, it only works if the  command 
"sudo systemctl stop guacd && sudo /usr/local/sbin/guacd -L debug -f" is running in the cli

I'm attaching a video

https://github.com/user-attachments/assets/dc03badd-349c-4862-bd34-76508a1374f4

**Comment by itiligent** [comment]
I cant replicate your issue on a native Debian system, but all logs point to an problem with your specific LXC enviroment and its handling of TLS.  What you are observing can be explained due to guacamole debug mode handling TLS differently between both connection methods.. which is a BIG clue. Study logs between a successful connection to WS2019 and debug mode logs to WS2012, to uncover any clear differences in each TLS connection negotiation. Are LXC TLS libraries and default settings backward compatible with earlier encryption ciphers or strengths? Another way may be to run up a test container and this time install the reverse proxy (which can be set to force older TLS as described above). Many questions I get tend to have a root cause of LXC not behaving identically to native Debian, so it might help to not assume all things are equal in your troubleshooting.
