### ISSUE TITLE
SSL - NGINX

### ISSUE THREAD

**Issue by larson-carter** [itiligent/Guacamole-Installer#64]
**Describe the issue:**
- When I run the 4b Script to install the SSL Cert, I am greeted with certbot error.

**Steps to reproduce the issue:**
- Open your directory of scripts
- Run the 4b install cert for nginx
- Everything "passes" then it throws a certbot error

**Describe the software environment:**
- Ubuntu 24.04 Virtualized
- Running guac (installed from this repo)
- Running HAProxy

**Logs / screenshots / error outputs etc**
<img width="1125" alt="Screenshot 2024-10-12 at 5 31 14 PM" src="https://github.com/user-attachments/assets/c567ed07-a3a9-418a-8277-847e8fe1e98c">

**Troubleshooting steps already taken?:**
- Rerunning script
- Manually installing SSL

**Comment by itiligent** [comment]
I cant reproduce your error on a fresh Ubuntu 24.04 system.  This script has been pretty heavily tested and not changed for some time.

I suspect your issue relates to the script variables such as $LE_DNS_NAME & $PROXY_SITE not being accurate. If you are running the 4b  script after the initial install you need to pay extra close attention to even minor chanages after original install as the script settings that are automatically updated only once at first install.  Check the 4b script settings are accurate for:
```
PROXY_SITE='make sure this is accurate to the local fqdn'
LE_DNS_NAME='make sure this public fqdn is published in public dns and reachable via 80 & 443'
```

when it all works you will see this:
![image](https://github.com/user-attachments/assets/7b0203f9-e27f-4f68-8194-6104db6465e2)

**Comment by itiligent** [comment]
I forgot to mention - you might have troubles running HA proxy and Nginx on the same system due to 80/443 conflics. Port 80 and 443 MUST also be forwared and available from the WAN for Certbot to work, as well as your public IP being published in public DNS. 

Firewall, DNS and NAT/network errors are almost always the reason for any failures with certbot, so your issue may be a combination of various things.

**Comment by larson-carter** [comment]
@itiligent 

Thank you for your reply,

I figured out the script core issue right after posting this here on GitHub. 

However, I am still having it fail when trying to install a cert.

I have 80/443 open and going to the guac server (ufw also allows them). I also do have it routed to my public DNS from my domain.

I'm starting to lean towards it being a Firewall issue, but I see all of the traffic flowing to it.

> "you might have troubles running HA proxy and Nginx on the same system due to 80/443 conflics"
- I considered this as well. I am only using HA Proxy for 3389 (RDP) traffic load balancing.
- The web stats is running on an entirely different port as well.
- Only process on 80/443 is-should be nginx.

**Comment by larson-carter** [comment]
Update. I solved this by doing the TXT record DNS validation.

Literally no other change. I do not understand why everything else I tried/did didn't work.
