### ISSUE TITLE
Customize Brand not working

### ISSUE THREAD

**Issue by morphyxz** [itiligent/Guacamole-Installer#65]
**Describe the issue:**
- When installing itiligent guacamole and trying to customize brand - no file with "custom-theme.css" files can be found

**Steps to reproduce the issue:**
- install a fresh ubuntu (with qemu-guest-agent) and install guacamole by itiligent

**Describe the software environment:**
- Ubuntu 24.04, fresh install, nothing else but apt upgrade and install guacamole

**Troubleshooting steps already taken?:**
- Reinstalled Ubuntu 24.04 to try from scratch before editing guacamole.properties, issue persists.

**Comment by itiligent** [comment]
I suspect you might be conflating 'installing guacmole' to also include your additional actions with customizing the branding.jar file? 

Lets take a step back...

The installer does not require you to edit guacomole.properties when customizing the branding. You have not explained why are you touching this file?  

The correct branding instructions are all in the readme, all you nee to do is modify the branding.jar file as you wish, then copy it back to /etc/guacamole/extensions and change permissions to 644. You also need to restart AND refresh client browser cache, hard reset in some cases.

**Comment by morphyxz** [comment]
oh wow I'm stupid.. I was looking for the files everywhere. haven't done it in a while. Forgot that I had to download them separately. I am so so sorry. Should have gone to sleep ha. Thank you! Closed

**Comment by itiligent** [comment]
closed this was a user config isssue
